### ISSUE TITLE
Strange error on heredoc

### ISSUE THREAD

**Issue by lud** [hrzndhrn/recode#17]
This code
```elixir
  def hello do
    """
    world
    """
    |> String.split()
  end
```

gets rewritten as:

```elixir
  def hello do
    "world
"
    |> nil
    |> String.split()
  end
  ```

**Comment by NickNeck** [comment]
That is really strange. I assume that is caused by `Recode.Task.SinglePipe`.
Would you expect that this will be rewritten to:
```elixir
def hello do
  String.split("""
  world
  """)
end
```

**Comment by lud** [comment]
Yes, I guess that somehow recode or sourceror detects a call in the AST that defines a multiline string, hence the `nil`.
