### ISSUE TITLE
Rename "SameLine" to "UnwrapLines"

### ISSUE THREAD

**Issue by tensiondriven** [hrzndhrn/recode#28]
As a followon from https://github.com/hrzndhrn/recode/issues/24, would it make sense to rename the `SameLine` feature to `UnwrapLines`?

I like `UnwrapLines` because it contains a verb, and is basically the opposite of "Wrapping Lines".  `UnwrapLines` or `UnwrapShortLines` would make more sense to me than `SameLine`.

Regardless of if you change it, I am thrilled to have this feature available – I was able to test this on a large project and it worked flawlessly.  After applying `SameLine`, `mix format` found no changes, which is perfect. Really, really wonderful.  Thank you!

**Comment by NickNeck** [comment]
Happy to hear that it works and that you like it.

I have renamed `SameLine` to `EnforceLineLength` already. But I see there are much more suggestions in the forum. What do you think about `PreferSameLine`?

**Comment by tensiondriven** [comment]
I'm fine with `EnforceLineLength` - I dont love `SameLine` or `PreferSameLine`, the word "Same" doesn't seem as accurate as it could be.  I really think it's fine if you keep it as `EnforceLineLength`, though since `mix format` already does this, the word "Enforce" is a little redundant. 

Since this is taking multi-line statements and reducing the number of lines they use, the words "Minimize" and "Unwrap"
 seem like appropriate verbs.  "Minimize" because it is minimizing the number of lines used for a statement, and "Unwrap" because it only acts on lines which were previous wrapped.  So, here are a few more ideas:

`UnwrapLines`
`UnwrapMultiline`
`UnwrapMultilineStatements` (or is this more accurately "Expressions"?)
`ReduceNewlines`
`MinimizeNewlines`
`RemoveExtraNewlines`

I still like "Unwrap" as the verb, as it's the inverse of what has happened to these lines, which is that they were wrapped.  

All that said, I'm thrilled with how this turned out and am happy with any of these.

**Comment by NickNeck** [comment]
Thanks for all the suggestions. 

> I'm fine with `EnforceLineLength`

I leave it then with `EnforceLineLength`
