### ISSUE TITLE
Failure expanding multi alias with __MODULE__ in the name

### ISSUE THREAD

**Issue by aaronrenner** [hrzndhrn/recode#57]
This is a great tool and I love how it took care of multi-alias expansion for me! Thank you!

I did find an issue where we get a warning if the file uses `alias __MODULE__.{A, B}`. The mix task outputs "Execution of the Recode.Task.AliasExpansion task failed." and then lists the filename. I manually fixed those and everything else worked great. Thanks!

**Comment by NickNeck** [comment]
Thank you for reporting this. I will take a look.
